# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 160d4ce648b2a7ae5ae8fed307502604eea124af1e66fcc9010c8af91be10f7ce78e3ca1a66341151c10f7f901e6128db777f4ff4f4f62c319ddec135d5234df

test:
  secret_key_base: 282bff1b54df169566b21451f8abae96e034bb47a8346944c10ff31a204de4f97c08fb0865016a4a8173f33930585d510da433c4479a410315e7c5654b043075

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
