source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.16'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets

gem 'jquery-rails'

# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

gem "twitter-bootstrap-rails"
gem 'active_model_serializers'
gem 'simple-rss'
gem 'awesome_print'
gem 'nokogiri'

group :development do
  gem "better_errors"
  gem "binding_of_caller"
end

group :development, :test do
  gem 'byebug'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'rspec-rails'
  gem 'faker'
  gem 'factory_girl_rails'
  gem 'quiet_assets'
  gem 'guard-rspec'
end
